"""phase4_documents_tracking

Revision ID: 94a04ba72517
Revises: e7f1b2c3d4e5
Create Date: 2026-09-03 23:20:43.219930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a04ba72517'
down_revision: Union[str, None] = 'e7f1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_access_logs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_access_logs_document_id'), 'document_access_logs', ['document_id'], unique=False)
    op.create_table('document_checklist_items',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('doc_type_code', sa.String(length=64), nullable=False),
    sa.Column('doc_name', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('approval_role', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_checklist_items_doc_type_code'), 'document_checklist_items', ['doc_type_code'], unique=False)
    op.create_index(op.f('ix_document_checklist_items_shipment_id'), 'document_checklist_items', ['shipment_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('document_name', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('version_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('documents', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=128), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=32), server_default='PENDING_REVIEW', nullable=False))
    op.add_column('documents', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('is_mandatory', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('documents', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_shipment_id'), 'documents', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.add_column('tracking_events', sa.Column('category', sa.String(length=32), server_default='TRANSPORT', nullable=False))
    op.add_column('tracking_events', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('tracking_events', sa.Column('event_time_original', sa.String(length=64), nullable=True))
    op.add_column('tracking_events', sa.Column('event_time_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tracking_events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tracking_events', sa.Column('source', sa.String(length=32), server_default='MANUAL', nullable=False))
    op.add_column('tracking_events', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('tracking_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tracking_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tracking_events_category'), 'tracking_events', ['category'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_time_utc'), 'tracking_events', ['event_time_utc'], unique=False)
    # Backfill event_time_utc from legacy event_time column if rows exist
    op.execute("UPDATE tracking_events SET event_time_utc = event_time WHERE event_time_utc IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_events_event_time_utc'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_category'), table_name='tracking_events')
    op.drop_column('tracking_events', 'updated_at')
    op.drop_column('tracking_events', 'created_at')
    op.drop_column('tracking_events', 'created_by')
    op.drop_column('tracking_events', 'source')
    op.drop_column('tracking_events', 'description')
    op.drop_column('tracking_events', 'event_time_utc')
    op.drop_column('tracking_events', 'event_time_original')
    op.drop_column('tracking_events', 'location')
    op.drop_column('tracking_events', 'category')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_shipment_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_column('documents', 'rejection_reason')
    op.drop_column('documents', 'is_mandatory')
    op.drop_column('documents', 'expiry_date')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'version_number')
    op.drop_column('documents', 'document_name')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_checklist_items_shipment_id'), table_name='document_checklist_items')
    op.drop_index(op.f('ix_document_checklist_items_doc_type_code'), table_name='document_checklist_items')
    op.drop_table('document_checklist_items')
    op.drop_index(op.f('ix_document_access_logs_document_id'), table_name='document_access_logs')
    op.drop_table('document_access_logs')
    # ### end Alembic commands ###
