"""
FreightCore Commercial Domain Interfaces / Ports (Team 2).

Defines abstract protocols for external dependencies (database, event bus,
rules engine, state machine, PDF generator) to ensure Hexagonal Architecture isolation.
"""

from __future__ import annotations

from typing import Protocol, Any
from datetime import date
from domain.entities import (
    Rfq, Rate, RateVersion, Route, Quotation, QuotationOption, Customer,
    Location, Carrier, ContainerType, Commodity, ExchangeRate, Job, MarginRule
)


class RfqRepositoryPort(Protocol):
    def save(self, rfq: Rfq) -> Rfq: ...
    def get_by_id(self, rfq_id: str) -> Rfq | None: ...
    def list_all(self, status: str | None = None, assigned_to: str | None = None) -> list[Rfq]: ...


class RateRepositoryPort(Protocol):
    def save_rate(self, rate: Rate) -> Rate: ...
    def get_rate_by_id(self, rate_id: str) -> Rate | None: ...
    def get_rate_version_by_id(self, version_id: str) -> RateVersion | None: ...
    def find_rates(
        self,
        origin_id: str,
        destination_id: str,
        effective_date: date,
        customer_id: str | None = None,
        commodity_id: str | None = None,
    ) -> list[Rate]: ...


class RouteRepositoryPort(Protocol):
    def save_route(self, route: Route) -> Route: ...
    def find_routes(self, origin_id: str, destination_id: str, mode: str) -> list[Route]: ...


class QuotationRepositoryPort(Protocol):
    def save_quotation(self, quotation: Quotation) -> Quotation: ...
    def get_by_id(self, quotation_id: str) -> Quotation | None: ...
    def get_by_rfq_id(self, rfq_id: str) -> list[Quotation]: ...


class CustomerRepositoryPort(Protocol):
    def get_customer_by_id(self, customer_id: str) -> Customer | None: ...
    def get_customer_exposure(self, customer_id: str) -> float: ...


class MasterDataRepositoryPort(Protocol):
    def get_location_by_id(self, location_id: str) -> Location | None: ...
    def get_carrier_by_id(self, carrier_id: str) -> Carrier | None: ...
    def get_container_type(self, code: str) -> ContainerType | None: ...
    def get_commodity_by_id(self, commodity_id: str) -> Commodity | None: ...


class ExchangeRatePort(Protocol):
    def get_exchange_rate(self, currency_code: str, effective_date: date) -> float: ...
    def convert(self, amount: float, from_currency: str, to_currency: str, effective_date: date) -> float: ...


class EventPublisherPort(Protocol):
    def publish(self, event_name: str, payload: dict[str, Any]) -> None: ...


class RulesEnginePort(Protocol):
    def get_margin_rules(self, service_type: str) -> list[MarginRule]: ...


class StateMachinePort(Protocol):
    def can_transition(self, entity_name: str, current_state: str, next_state: str) -> bool: ...
    def transition(self, entity_name: str, entity_id: str, from_state: str, to_state: str, actor_id: str) -> None: ...


class PdfGeneratorPort(Protocol):
    def generate_quotation_pdf(self, quotation: Quotation, rfq: Rfq, customer: Customer) -> bytes: ...
