"""Fix DocumentApproval CASCADE

Revision ID: 0997e5b5d787
Revises: 2e8da72c3e8d
Create Date: 2026-09-04 06:16:14.838844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0997e5b5d787'
down_revision: Union[str, None] = '2e8da72c3e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_approvals_document_id_fkey'), 'document_approvals', type_='foreignkey')
    op.create_foreign_key(None, 'document_approvals', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_approvals', type_='foreignkey')
    op.create_foreign_key(op.f('document_approvals_document_id_fkey'), 'document_approvals', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
