"""Add missing Team 3 entities

Revision ID: 2e8da72c3e8d
Revises: e61698263522
Create Date: 2026-09-04 05:22:43.948448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8da72c3e8d'
down_revision: Union[str, None] = 'e61698263522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_bulk_exceptions',
    sa.Column('consolidation_id', sa.UUID(), nullable=True),
    sa.Column('exception_type', sa.String(length=64), nullable=True),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_bulk_exceptions_tenant_id'), 'break_bulk_exceptions', ['tenant_id'], unique=False)
    op.create_table('carrier_scores',
    sa.Column('carrier_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('period', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_scores_tenant_id'), 'carrier_scores', ['tenant_id'], unique=False)
    op.create_table('cost_allocations',
    sa.Column('consolidation_id', sa.UUID(), nullable=True),
    sa.Column('house_id', sa.UUID(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_allocations_tenant_id'), 'cost_allocations', ['tenant_id'], unique=False)
    op.create_table('customs_rules',
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customs_rules_tenant_id'), 'customs_rules', ['tenant_id'], unique=False)
    op.create_table('demurrage_rules',
    sa.Column('carrier_id', sa.UUID(), nullable=True),
    sa.Column('port_id', sa.UUID(), nullable=True),
    sa.Column('free_days', sa.Integer(), nullable=True),
    sa.Column('daily_rate', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demurrage_rules_tenant_id'), 'demurrage_rules', ['tenant_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('run_date', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_tenant_id'), 'reconciliation_runs', ['tenant_id'], unique=False)
    op.create_table('sanctions_list_versions',
    sa.Column('version_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_list_versions_tenant_id'), 'sanctions_list_versions', ['tenant_id'], unique=False)
    op.create_table('market_rates',
    sa.Column('origin_location_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('rate_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'origin_location_id', 'destination_location_id', 'mode', 'rate_type', 'effective_date', 'source', name='uq_market_rate')
    )
    op.create_index(op.f('ix_market_rates_tenant_id'), 'market_rates', ['tenant_id'], unique=False)
    op.create_index('ix_mr_effective_expiry', 'market_rates', ['effective_date', 'expiry_date'], unique=False)
    op.create_index('ix_mr_tenant_lane', 'market_rates', ['tenant_id', 'origin_location_id', 'destination_location_id'], unique=False)
    op.create_table('ar_aging_snapshots',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('current_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('over_30_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_aging_snapshots_tenant_id'), 'ar_aging_snapshots', ['tenant_id'], unique=False)
    op.create_table('ar_payments',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ar_payments_tenant_id'), 'ar_payments', ['tenant_id'], unique=False)
    op.create_table('flight_manifests',
    sa.Column('flight_id', sa.UUID(), nullable=True),
    sa.Column('total_weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_volume', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_schedules.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_manifests_tenant_id'), 'flight_manifests', ['tenant_id'], unique=False)
    op.create_table('agent_assignments',
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_assignments_tenant_id'), 'agent_assignments', ['tenant_id'], unique=False)
    op.create_table('job_tasks',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_tasks_job_id'), 'job_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_tasks_tenant_id'), 'job_tasks', ['tenant_id'], unique=False)
    op.create_table('bills_of_lading',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('bl_number', sa.String(length=64), nullable=True),
    sa.Column('bl_type', sa.String(length=16), nullable=True),
    sa.Column('parent_bl_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_bl_id'], ['bills_of_lading.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_of_lading_tenant_id'), 'bills_of_lading', ['tenant_id'], unique=False)
    op.create_table('cargo_acceptances',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('pieces_received', sa.Integer(), nullable=True),
    sa.Column('pieces_accepted', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('screening_status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_acceptances_tenant_id'), 'cargo_acceptances', ['tenant_id'], unique=False)
    op.create_table('claims',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('claim_type', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_table('customs_declarations',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('hs_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customs_declarations_tenant_id'), 'customs_declarations', ['tenant_id'], unique=False)
    op.create_table('dgr_declarations',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('un_number', sa.String(length=16), nullable=True),
    sa.Column('class_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dgr_declarations_tenant_id'), 'dgr_declarations', ['tenant_id'], unique=False)
    op.create_table('pod_records',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('delivery_timestamp', sa.String(length=64), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('signature_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_records_tenant_id'), 'pod_records', ['tenant_id'], unique=False)
    op.create_table('vendor_bill_discrepancies',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('contracted_rate_id', sa.UUID(), nullable=True),
    sa.Column('contracted_rate_version_id', sa.UUID(), nullable=True),
    sa.Column('shipment_reference', sa.Text(), nullable=True),
    sa.Column('vendor_invoice_reference', sa.Text(), nullable=True),
    sa.Column('charge_code', sa.Text(), nullable=True),
    sa.Column('contracted_rate_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('invoiced_rate_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('rate_effective_date', sa.Date(), nullable=True),
    sa.Column('rate_expiry_date', sa.Date(), nullable=True),
    sa.Column('rate_was_expired_at_invoice_date', sa.Boolean(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contracted_rate_id'], ['rates.id'], ),
    sa.ForeignKeyConstraint(['contracted_rate_version_id'], ['rate_versions.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vbd_detected_at', 'vendor_bill_discrepancies', ['detected_at'], unique=False)
    op.create_index('ix_vbd_shipment_id', 'vendor_bill_discrepancies', ['shipment_id'], unique=False)
    op.create_index('ix_vbd_tenant_status', 'vendor_bill_discrepancies', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_vbd_vendor_id', 'vendor_bill_discrepancies', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_bill_discrepancies_status'), 'vendor_bill_discrepancies', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_bill_discrepancies_tenant_id'), 'vendor_bill_discrepancies', ['tenant_id'], unique=False)
    op.create_table('air_consolidations',
    sa.Column('master_awb_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_awb_id'], ['awb_records.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_air_consolidations_tenant_id'), 'air_consolidations', ['tenant_id'], unique=False)
    op.create_table('demurrage_accruals',
    sa.Column('container_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demurrage_accruals_tenant_id'), 'demurrage_accruals', ['tenant_id'], unique=False)
    op.create_table('demurrage_overrides',
    sa.Column('container_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('new_free_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demurrage_overrides_tenant_id'), 'demurrage_overrides', ['tenant_id'], unique=False)
    op.create_table('dgr_approvals',
    sa.Column('declaration_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['declaration_id'], ['dgr_declarations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dgr_approvals_tenant_id'), 'dgr_approvals', ['tenant_id'], unique=False)
    op.create_table('document_access_logs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_access_logs_document_id'), 'document_access_logs', ['document_id'], unique=False)
    op.create_table('document_approvals',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_approvals_tenant_id'), 'document_approvals', ['tenant_id'], unique=False)
    op.create_table('document_checklist_items',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('doc_type_code', sa.String(length=64), nullable=False),
    sa.Column('doc_name', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('approval_role', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_checklist_items_doc_type_code'), 'document_checklist_items', ['doc_type_code'], unique=False)
    op.create_index(op.f('ix_document_checklist_items_shipment_id'), 'document_checklist_items', ['shipment_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('eta_history',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('leg_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('value', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leg_id'], ['shipment_legs.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eta_history_leg_id'), 'eta_history', ['leg_id'], unique=False)
    op.create_index(op.f('ix_eta_history_shipment_id'), 'eta_history', ['shipment_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('revenue_line_id', sa.UUID(), nullable=True),
    sa.Column('charge_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revenue_line_id'], ['revenue_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_revenue_line_id'), 'invoice_lines', ['revenue_line_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_tenant_id'), 'invoice_lines', ['tenant_id'], unique=False)
    op.create_table('sea_consolidations',
    sa.Column('master_bl_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_bl_id'], ['bills_of_lading.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sea_consolidations_tenant_id'), 'sea_consolidations', ['tenant_id'], unique=False)
    op.create_table('vgm_records',
    sa.Column('container_id', sa.UUID(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vgm_records_tenant_id'), 'vgm_records', ['tenant_id'], unique=False)
    op.create_table('agent_settlements',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('rate_agreement_id', sa.UUID(), nullable=True),
    sa.Column('rate_version_id', sa.UUID(), nullable=True),
    sa.Column('cost_entry_id', sa.UUID(), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('settlement_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('rate_effective_date', sa.Date(), nullable=True),
    sa.Column('rate_expiry_date', sa.Date(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cost_entry_id'], ['financial_entries.id'], ),
    sa.ForeignKeyConstraint(['rate_agreement_id'], ['agent_rate_agreements.id'], ),
    sa.ForeignKeyConstraint(['rate_version_id'], ['rate_versions.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_settlements_status'), 'agent_settlements', ['status'], unique=False)
    op.create_index(op.f('ix_agent_settlements_tenant_id'), 'agent_settlements', ['tenant_id'], unique=False)
    op.create_index('ix_as_agent_id', 'agent_settlements', ['agent_id'], unique=False)
    op.create_index('ix_as_settlement_date', 'agent_settlements', ['settlement_date'], unique=False)
    op.create_index('ix_as_shipment_id', 'agent_settlements', ['shipment_id'], unique=False)
    op.create_index('ix_as_tenant_status', 'agent_settlements', ['tenant_id', 'status'], unique=False)
    op.create_table('credit_notes',
    sa.Column('credit_note_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('credit_note_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('financial_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['financial_entry_id'], ['financial_entries.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'credit_note_number', name='uq_credit_note_number')
    )
    op.create_index(op.f('ix_credit_notes_credit_note_number'), 'credit_notes', ['credit_note_number'], unique=False)
    op.create_index(op.f('ix_credit_notes_customer_id'), 'credit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_invoice_id'), 'credit_notes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_tenant_id'), 'credit_notes', ['tenant_id'], unique=False)
    op.create_table('debit_notes',
    sa.Column('debit_note_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('charge_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('debit_note_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('financial_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['financial_entry_id'], ['financial_entries.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'debit_note_number', name='uq_debit_note_number')
    )
    op.create_index(op.f('ix_debit_notes_customer_id'), 'debit_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_debit_notes_debit_note_number'), 'debit_notes', ['debit_note_number'], unique=False)
    op.create_index(op.f('ix_debit_notes_invoice_id'), 'debit_notes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_debit_notes_tenant_id'), 'debit_notes', ['tenant_id'], unique=False)
    op.create_table('payables',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('carrier_id', sa.UUID(), nullable=True),
    sa.Column('bill_number', sa.String(length=64), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('supporting_document_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('financial_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['financial_entry_id'], ['financial_entries.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'bill_number', name='uq_payable_bill_number')
    )
    op.create_index(op.f('ix_payables_approval_status'), 'payables', ['approval_status'], unique=False)
    op.create_index(op.f('ix_payables_bill_number'), 'payables', ['bill_number'], unique=False)
    op.create_index(op.f('ix_payables_carrier_id'), 'payables', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_payables_shipment_id'), 'payables', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_payables_status'), 'payables', ['status'], unique=False)
    op.create_index(op.f('ix_payables_tenant_id'), 'payables', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_payables_vendor_id'), 'payables', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_payables_verification_status'), 'payables', ['verification_status'], unique=False)
    op.create_table('payable_lines',
    sa.Column('payable_id', sa.UUID(), nullable=False),
    sa.Column('cost_line_id', sa.UUID(), nullable=True),
    sa.Column('charge_code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('billed_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_line_id'], ['cost_lines.id'], ),
    sa.ForeignKeyConstraint(['payable_id'], ['payables.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payable_lines_cost_line_id'), 'payable_lines', ['cost_line_id'], unique=False)
    op.create_index(op.f('ix_payable_lines_payable_id'), 'payable_lines', ['payable_id'], unique=False)
    op.create_index(op.f('ix_payable_lines_tenant_id'), 'payable_lines', ['tenant_id'], unique=False)
    op.create_table('payable_payments',
    sa.Column('payable_id', sa.UUID(), nullable=False),
    sa.Column('payment_reference', sa.String(length=64), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('financial_entry_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_entry_id'], ['financial_entries.id'], ),
    sa.ForeignKeyConstraint(['payable_id'], ['payables.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payable_payments_payable_id'), 'payable_payments', ['payable_id'], unique=False)
    op.create_index(op.f('ix_payable_payments_payment_reference'), 'payable_payments', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_payable_payments_tenant_id'), 'payable_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_awb_records_tenant_id'), 'awb_records', ['tenant_id'], unique=False)
    op.add_column('cost_lines', sa.Column('carrier_id', sa.UUID(), nullable=True))
    op.add_column('cost_lines', sa.Column('charge_code', sa.Text(), nullable=True))
    op.add_column('cost_lines', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('cost_lines', sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False))
    op.add_column('cost_lines', sa.Column('unit_rate', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('cost_lines', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('cost_lines', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('cost_lines', sa.Column('is_additional', sa.Boolean(), nullable=False))
    op.add_column('cost_lines', sa.Column('quotation_line_id', sa.UUID(), nullable=True))
    op.add_column('cost_lines', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_cost_lines_carrier_id'), 'cost_lines', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_cost_lines_shipment_id'), 'cost_lines', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_cost_lines_status'), 'cost_lines', ['status'], unique=False)
    op.create_index(op.f('ix_cost_lines_vendor_id'), 'cost_lines', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'cost_lines', 'quotation_lines', ['quotation_line_id'], ['id'])
    op.create_foreign_key(None, 'cost_lines', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'cost_lines', 'carriers', ['carrier_id'], ['id'])
    op.add_column('documents', sa.Column('document_name', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('version_number', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=128), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('documents', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('is_mandatory', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_shipment_id'), 'documents', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.add_column('financial_entries', sa.Column('reversal_reason', sa.Text(), nullable=True))
    op.add_column('financial_entries', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('financial_entries', sa.Column('revenue_line_id', sa.UUID(), nullable=True))
    op.add_column('financial_entries', sa.Column('cost_line_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'financial_entries', 'cost_lines', ['cost_line_id'], ['id'])
    op.create_foreign_key(None, 'financial_entries', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'financial_entries', 'revenue_lines', ['revenue_line_id'], ['id'])
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('currency_code', sa.String(length=3), nullable=False))
    op.add_column('invoices', sa.Column('exchange_rate_to_base', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('invoices', sa.Column('exchange_rate_source', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False))
    op.add_column('invoices', sa.Column('tax_jurisdiction', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('invoices', sa.Column('tax_type', sa.String(length=32), nullable=True))
    op.add_column('invoices', sa.Column('job_number', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('bl_awb_number', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('customer_po', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('quotation_id', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('approval_status', sa.String(length=32), nullable=False))
    op.add_column('invoices', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('sent_by', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('payment_terms', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_shipment_id'), 'invoices', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_unique_constraint('uq_invoice_number', 'invoices', ['tenant_id', 'invoice_number'])
    op.create_foreign_key(None, 'invoices', 'quotations', ['quotation_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'users', ['sent_by'], ['id'])
    op.create_foreign_key(None, 'invoices', 'users', ['approved_by'], ['id'])
    op.create_index(op.f('ix_notification_events_tenant_id'), 'notification_events', ['tenant_id'], unique=False)
    op.add_column('revenue_lines', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('revenue_lines', sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False))
    op.add_column('revenue_lines', sa.Column('unit_rate', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('revenue_lines', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('revenue_lines', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('revenue_lines', sa.Column('is_additional', sa.Boolean(), nullable=False))
    op.add_column('revenue_lines', sa.Column('quotation_line_id', sa.UUID(), nullable=True))
    op.add_column('revenue_lines', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_revenue_lines_shipment_id'), 'revenue_lines', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_revenue_lines_status'), 'revenue_lines', ['status'], unique=False)
    op.create_foreign_key(None, 'revenue_lines', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'revenue_lines', 'quotation_lines', ['quotation_line_id'], ['id'])
    op.create_index(op.f('ix_sea_shipment_details_tenant_id'), 'sea_shipment_details', ['tenant_id'], unique=False)
    op.add_column('shipment_exceptions', sa.Column('domain', sa.String(length=32), nullable=False))
    op.add_column('shipment_exceptions', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('shipment_exceptions', sa.Column('financial_impact_estimated', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('shipment_exceptions', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.add_column('shipment_exceptions', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('shipment_exceptions', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipment_exceptions', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipment_exceptions', sa.Column('resolution_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_shipment_exceptions_domain'), 'shipment_exceptions', ['domain'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_exception_type'), 'shipment_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_severity'), 'shipment_exceptions', ['severity'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_shipment_id'), 'shipment_exceptions', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_status'), 'shipment_exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_shipment_exceptions_tenant_id'), 'shipment_exceptions', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('shipment_exceptions_created_by_fkey'), 'shipment_exceptions', type_='foreignkey')
    op.drop_constraint(op.f('shipment_exceptions_updated_by_fkey'), 'shipment_exceptions', type_='foreignkey')
    op.drop_column('shipment_exceptions', 'created_by')
    op.drop_column('shipment_exceptions', 'details')
    op.drop_column('shipment_exceptions', 'updated_by')
    op.add_column('shipments', sa.Column('job_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'shipments', ['job_id'])
    op.create_foreign_key(None, 'shipments', 'jobs', ['job_id'], ['id'])
    op.add_column('tracking_events', sa.Column('category', sa.String(length=32), nullable=False))
    op.add_column('tracking_events', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('tracking_events', sa.Column('event_time_original', sa.String(length=64), nullable=True))
    op.add_column('tracking_events', sa.Column('event_time_utc', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tracking_events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tracking_events', sa.Column('source', sa.String(length=32), nullable=False))
    op.add_column('tracking_events', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('tracking_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tracking_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_tracking_events_category'), 'tracking_events', ['category'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_time_utc'), 'tracking_events', ['event_time_utc'], unique=False)
    op.create_index(op.f('ix_uld_assignments_tenant_id'), 'uld_assignments', ['tenant_id'], unique=False)
    op.add_column('zones', sa.Column('cities', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'cities')
    op.drop_index(op.f('ix_uld_assignments_tenant_id'), table_name='uld_assignments')
    op.drop_index(op.f('ix_tracking_events_event_time_utc'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_category'), table_name='tracking_events')
    op.drop_column('tracking_events', 'updated_at')
    op.drop_column('tracking_events', 'created_at')
    op.drop_column('tracking_events', 'created_by')
    op.drop_column('tracking_events', 'source')
    op.drop_column('tracking_events', 'description')
    op.drop_column('tracking_events', 'event_time_utc')
    op.drop_column('tracking_events', 'event_time_original')
    op.drop_column('tracking_events', 'location')
    op.drop_column('tracking_events', 'category')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_constraint(None, 'shipments', type_='unique')
    op.drop_column('shipments', 'job_id')
    op.add_column('shipment_exceptions', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('shipment_exceptions', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('shipment_exceptions', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('shipment_exceptions_updated_by_fkey'), 'shipment_exceptions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('shipment_exceptions_created_by_fkey'), 'shipment_exceptions', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_shipment_exceptions_tenant_id'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_status'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_shipment_id'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_severity'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_exception_type'), table_name='shipment_exceptions')
    op.drop_index(op.f('ix_shipment_exceptions_domain'), table_name='shipment_exceptions')
    op.drop_column('shipment_exceptions', 'resolution_notes')
    op.drop_column('shipment_exceptions', 'resolved_at')
    op.drop_column('shipment_exceptions', 'acknowledged_at')
    op.drop_column('shipment_exceptions', 'opened_at')
    op.drop_column('shipment_exceptions', 'owner_id')
    op.drop_column('shipment_exceptions', 'financial_impact_estimated')
    op.drop_column('shipment_exceptions', 'description')
    op.drop_column('shipment_exceptions', 'domain')
    op.drop_index(op.f('ix_sea_shipment_details_tenant_id'), table_name='sea_shipment_details')
    op.drop_constraint(None, 'revenue_lines', type_='foreignkey')
    op.drop_constraint(None, 'revenue_lines', type_='foreignkey')
    op.drop_index(op.f('ix_revenue_lines_status'), table_name='revenue_lines')
    op.drop_index(op.f('ix_revenue_lines_shipment_id'), table_name='revenue_lines')
    op.drop_column('revenue_lines', 'created_by')
    op.drop_column('revenue_lines', 'quotation_line_id')
    op.drop_column('revenue_lines', 'is_additional')
    op.drop_column('revenue_lines', 'status')
    op.drop_column('revenue_lines', 'currency_code')
    op.drop_column('revenue_lines', 'unit_rate')
    op.drop_column('revenue_lines', 'quantity')
    op.drop_column('revenue_lines', 'description')
    op.drop_index(op.f('ix_notification_events_tenant_id'), table_name='notification_events')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint('uq_invoice_number', 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_shipment_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'payment_terms')
    op.drop_column('invoices', 'customer_email')
    op.drop_column('invoices', 'sent_by')
    op.drop_column('invoices', 'sent_at')
    op.drop_column('invoices', 'approved_at')
    op.drop_column('invoices', 'approved_by')
    op.drop_column('invoices', 'approval_status')
    op.drop_column('invoices', 'quotation_id')
    op.drop_column('invoices', 'customer_po')
    op.drop_column('invoices', 'bl_awb_number')
    op.drop_column('invoices', 'job_number')
    op.drop_column('invoices', 'tax_type')
    op.drop_column('invoices', 'tax_rate')
    op.drop_column('invoices', 'tax_jurisdiction')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'subtotal_amount')
    op.drop_column('invoices', 'exchange_rate_source')
    op.drop_column('invoices', 'exchange_rate_to_base')
    op.drop_column('invoices', 'currency_code')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'invoice_date')
    op.drop_column('invoices', 'invoice_number')
    op.drop_constraint(None, 'financial_entries', type_='foreignkey')
    op.drop_constraint(None, 'financial_entries', type_='foreignkey')
    op.drop_constraint(None, 'financial_entries', type_='foreignkey')
    op.drop_column('financial_entries', 'cost_line_id')
    op.drop_column('financial_entries', 'revenue_line_id')
    op.drop_column('financial_entries', 'approved_by')
    op.drop_column('financial_entries', 'reversal_reason')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_shipment_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_column('documents', 'rejection_reason')
    op.drop_column('documents', 'is_mandatory')
    op.drop_column('documents', 'expiry_date')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'version_number')
    op.drop_column('documents', 'document_name')
    op.drop_constraint(None, 'cost_lines', type_='foreignkey')
    op.drop_constraint(None, 'cost_lines', type_='foreignkey')
    op.drop_constraint(None, 'cost_lines', type_='foreignkey')
    op.drop_index(op.f('ix_cost_lines_vendor_id'), table_name='cost_lines')
    op.drop_index(op.f('ix_cost_lines_status'), table_name='cost_lines')
    op.drop_index(op.f('ix_cost_lines_shipment_id'), table_name='cost_lines')
    op.drop_index(op.f('ix_cost_lines_carrier_id'), table_name='cost_lines')
    op.drop_column('cost_lines', 'created_by')
    op.drop_column('cost_lines', 'quotation_line_id')
    op.drop_column('cost_lines', 'is_additional')
    op.drop_column('cost_lines', 'status')
    op.drop_column('cost_lines', 'currency_code')
    op.drop_column('cost_lines', 'unit_rate')
    op.drop_column('cost_lines', 'quantity')
    op.drop_column('cost_lines', 'description')
    op.drop_column('cost_lines', 'charge_code')
    op.drop_column('cost_lines', 'carrier_id')
    op.drop_index(op.f('ix_awb_records_tenant_id'), table_name='awb_records')
    op.drop_index(op.f('ix_payable_payments_tenant_id'), table_name='payable_payments')
    op.drop_index(op.f('ix_payable_payments_payment_reference'), table_name='payable_payments')
    op.drop_index(op.f('ix_payable_payments_payable_id'), table_name='payable_payments')
    op.drop_table('payable_payments')
    op.drop_index(op.f('ix_payable_lines_tenant_id'), table_name='payable_lines')
    op.drop_index(op.f('ix_payable_lines_payable_id'), table_name='payable_lines')
    op.drop_index(op.f('ix_payable_lines_cost_line_id'), table_name='payable_lines')
    op.drop_table('payable_lines')
    op.drop_index(op.f('ix_payables_verification_status'), table_name='payables')
    op.drop_index(op.f('ix_payables_vendor_id'), table_name='payables')
    op.drop_index(op.f('ix_payables_tenant_id'), table_name='payables')
    op.drop_index(op.f('ix_payables_status'), table_name='payables')
    op.drop_index(op.f('ix_payables_shipment_id'), table_name='payables')
    op.drop_index(op.f('ix_payables_carrier_id'), table_name='payables')
    op.drop_index(op.f('ix_payables_bill_number'), table_name='payables')
    op.drop_index(op.f('ix_payables_approval_status'), table_name='payables')
    op.drop_table('payables')
    op.drop_index(op.f('ix_debit_notes_tenant_id'), table_name='debit_notes')
    op.drop_index(op.f('ix_debit_notes_invoice_id'), table_name='debit_notes')
    op.drop_index(op.f('ix_debit_notes_debit_note_number'), table_name='debit_notes')
    op.drop_index(op.f('ix_debit_notes_customer_id'), table_name='debit_notes')
    op.drop_table('debit_notes')
    op.drop_index(op.f('ix_credit_notes_tenant_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_invoice_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_customer_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_credit_note_number'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index('ix_as_tenant_status', table_name='agent_settlements')
    op.drop_index('ix_as_shipment_id', table_name='agent_settlements')
    op.drop_index('ix_as_settlement_date', table_name='agent_settlements')
    op.drop_index('ix_as_agent_id', table_name='agent_settlements')
    op.drop_index(op.f('ix_agent_settlements_tenant_id'), table_name='agent_settlements')
    op.drop_index(op.f('ix_agent_settlements_status'), table_name='agent_settlements')
    op.drop_table('agent_settlements')
    op.drop_index(op.f('ix_vgm_records_tenant_id'), table_name='vgm_records')
    op.drop_table('vgm_records')
    op.drop_index(op.f('ix_sea_consolidations_tenant_id'), table_name='sea_consolidations')
    op.drop_table('sea_consolidations')
    op.drop_index(op.f('ix_invoice_lines_tenant_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_revenue_line_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_eta_history_shipment_id'), table_name='eta_history')
    op.drop_index(op.f('ix_eta_history_leg_id'), table_name='eta_history')
    op.drop_table('eta_history')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_checklist_items_shipment_id'), table_name='document_checklist_items')
    op.drop_index(op.f('ix_document_checklist_items_doc_type_code'), table_name='document_checklist_items')
    op.drop_table('document_checklist_items')
    op.drop_index(op.f('ix_document_approvals_tenant_id'), table_name='document_approvals')
    op.drop_table('document_approvals')
    op.drop_index(op.f('ix_document_access_logs_document_id'), table_name='document_access_logs')
    op.drop_table('document_access_logs')
    op.drop_index(op.f('ix_dgr_approvals_tenant_id'), table_name='dgr_approvals')
    op.drop_table('dgr_approvals')
    op.drop_index(op.f('ix_demurrage_overrides_tenant_id'), table_name='demurrage_overrides')
    op.drop_table('demurrage_overrides')
    op.drop_index(op.f('ix_demurrage_accruals_tenant_id'), table_name='demurrage_accruals')
    op.drop_table('demurrage_accruals')
    op.drop_index(op.f('ix_air_consolidations_tenant_id'), table_name='air_consolidations')
    op.drop_table('air_consolidations')
    op.drop_index(op.f('ix_vendor_bill_discrepancies_tenant_id'), table_name='vendor_bill_discrepancies')
    op.drop_index(op.f('ix_vendor_bill_discrepancies_status'), table_name='vendor_bill_discrepancies')
    op.drop_index('ix_vbd_vendor_id', table_name='vendor_bill_discrepancies')
    op.drop_index('ix_vbd_tenant_status', table_name='vendor_bill_discrepancies')
    op.drop_index('ix_vbd_shipment_id', table_name='vendor_bill_discrepancies')
    op.drop_index('ix_vbd_detected_at', table_name='vendor_bill_discrepancies')
    op.drop_table('vendor_bill_discrepancies')
    op.drop_index(op.f('ix_pod_records_tenant_id'), table_name='pod_records')
    op.drop_table('pod_records')
    op.drop_index(op.f('ix_dgr_declarations_tenant_id'), table_name='dgr_declarations')
    op.drop_table('dgr_declarations')
    op.drop_index(op.f('ix_customs_declarations_tenant_id'), table_name='customs_declarations')
    op.drop_table('customs_declarations')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_cargo_acceptances_tenant_id'), table_name='cargo_acceptances')
    op.drop_table('cargo_acceptances')
    op.drop_index(op.f('ix_bills_of_lading_tenant_id'), table_name='bills_of_lading')
    op.drop_table('bills_of_lading')
    op.drop_index(op.f('ix_job_tasks_tenant_id'), table_name='job_tasks')
    op.drop_index(op.f('ix_job_tasks_job_id'), table_name='job_tasks')
    op.drop_table('job_tasks')
    op.drop_index(op.f('ix_agent_assignments_tenant_id'), table_name='agent_assignments')
    op.drop_table('agent_assignments')
    op.drop_index(op.f('ix_flight_manifests_tenant_id'), table_name='flight_manifests')
    op.drop_table('flight_manifests')
    op.drop_index(op.f('ix_ar_payments_tenant_id'), table_name='ar_payments')
    op.drop_table('ar_payments')
    op.drop_index(op.f('ix_ar_aging_snapshots_tenant_id'), table_name='ar_aging_snapshots')
    op.drop_table('ar_aging_snapshots')
    op.drop_index('ix_mr_tenant_lane', table_name='market_rates')
    op.drop_index('ix_mr_effective_expiry', table_name='market_rates')
    op.drop_index(op.f('ix_market_rates_tenant_id'), table_name='market_rates')
    op.drop_table('market_rates')
    op.drop_index(op.f('ix_sanctions_list_versions_tenant_id'), table_name='sanctions_list_versions')
    op.drop_table('sanctions_list_versions')
    op.drop_index(op.f('ix_reconciliation_runs_tenant_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_demurrage_rules_tenant_id'), table_name='demurrage_rules')
    op.drop_table('demurrage_rules')
    op.drop_index(op.f('ix_customs_rules_tenant_id'), table_name='customs_rules')
    op.drop_table('customs_rules')
    op.drop_index(op.f('ix_cost_allocations_tenant_id'), table_name='cost_allocations')
    op.drop_table('cost_allocations')
    op.drop_index(op.f('ix_carrier_scores_tenant_id'), table_name='carrier_scores')
    op.drop_table('carrier_scores')
    op.drop_index(op.f('ix_break_bulk_exceptions_tenant_id'), table_name='break_bulk_exceptions')
    op.drop_table('break_bulk_exceptions')
    # ### end Alembic commands ###
