"""initial_schema

Revision ID: a0a2948c1dc5
Revises: 
Create Date: 2026-09-02 07:58:08.289450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0a2948c1dc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('carriers',
    sa.Column('carrier_type', sa.String(length=32), nullable=False),
    sa.Column('scac_code', sa.Text(), nullable=True),
    sa.Column('iata_code', sa.CHAR(length=2), nullable=True),
    sa.Column('iata_prefix', sa.CHAR(length=3), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_nvocc', sa.Boolean(), nullable=False),
    sa.Column('hub_locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge_codes',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('charge_type', sa.String(length=32), nullable=False),
    sa.Column('rate_basis', sa.String(length=32), nullable=False),
    sa.Column('applicable_mode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('commodities',
    sa.Column('hs_code', sa.CHAR(length=6), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_dgr', sa.Boolean(), nullable=False),
    sa.Column('export_restricted', sa.Boolean(), nullable=False),
    sa.Column('import_restricted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_hs_code'), 'commodities', ['hs_code'], unique=False)
    op.create_table('container_types',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('cbm_capacity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('max_payload_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('countries',
    sa.Column('iso_code', sa.CHAR(length=2), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('trade_zone', sa.Text(), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('requires_permit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('currencies',
    sa.Column('code', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('dim_carriers',
    sa.Column('source_carrier_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('carrier_type', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_customers',
    sa.Column('source_customer_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('credit_tier', sa.String(length=16), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_routes',
    sa.Column('source_route_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_time',
    sa.Column('date_key', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_key')
    )
    op.create_table('document_types',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('applicable_mode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('fact_financial_entries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_entry_id', sa.UUID(), nullable=False),
    sa.Column('time_dim_id', sa.UUID(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_shipments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_shipment_id', sa.UUID(), nullable=False),
    sa.Column('customer_dim_id', sa.UUID(), nullable=True),
    sa.Column('route_dim_id', sa.UUID(), nullable=True),
    sa.Column('time_dim_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_tracking_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('time_dim_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incoterms',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publication_status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_table('package_types',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('processed_events',
    sa.Column('consumer_name', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_name', 'event_id', name='uq_consumer_event')
    )
    op.create_table('tenants',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('uld_types',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('volume_cbm', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('exchange_rates',
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code', 'rate_date', 'source', name='uq_exchange_rate')
    )
    op.create_table('locations',
    sa.Column('un_locode', sa.Text(), nullable=True),
    sa.Column('iata_code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code'),
    sa.UniqueConstraint('un_locode')
    )
    op.create_table('reconciliation_variances',
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_variances_tenant_id'), 'reconciliation_variances', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_role_tenant_code')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('sla_definitions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=True),
    sa.Column('service_type', sa.String(length=32), nullable=True),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('pause_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_definitions_tenant_id'), 'sla_definitions', ['tenant_id'], unique=False)
    op.create_table('state_machines',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_state_machine_code')
    )
    op.create_index(op.f('ix_state_machines_tenant_id'), 'state_machines', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('mfa_recovery_hashes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('vessels',
    sa.Column('imo_number', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('flag', sa.Text(), nullable=True),
    sa.Column('owner_carrier_id', sa.UUID(), nullable=False),
    sa.Column('teu_capacity', sa.Integer(), nullable=True),
    sa.Column('vessel_type', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo_number')
    )
    op.create_table('zones',
    sa.Column('zone_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('business_rules',
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'domain', 'code', name='uq_rule_domain_code')
    )
    op.create_index(op.f('ix_business_rules_tenant_id'), 'business_rules', ['tenant_id'], unique=False)
    op.create_table('companies',
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_company_tenant_code')
    )
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tax_registration_encrypted', sa.Text(), nullable=True),
    sa.Column('registration_number', sa.Text(), nullable=True),
    sa.Column('iata_fiata_membership', sa.Text(), nullable=True),
    sa.Column('credit_limit_amount_encrypted', sa.Text(), nullable=True),
    sa.Column('credit_limit_currency', sa.CHAR(length=3), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('credit_tier', sa.String(length=16), nullable=False),
    sa.Column('preferred_lanes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_service_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kyc_status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credit_limit_currency'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_code', name='uq_customer_code')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('flight_schedules',
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('origin_location_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('flight_number', sa.Text(), nullable=False),
    sa.Column('frequency', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('scheduled_departure', sa.Text(), nullable=True),
    sa.Column('scheduled_arrival', sa.Text(), nullable=True),
    sa.Column('cargo_cutoff', sa.Text(), nullable=True),
    sa.Column('documentation_cutoff', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('device_info', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('routes',
    sa.Column('origin_location_id', sa.UUID(), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_tenant_id'), 'routes', ['tenant_id'], unique=False)
    op.create_table('sla_clocks',
    sa.Column('sla_definition_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sla_definition_id'], ['sla_definitions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_clocks_entity_id'), 'sla_clocks', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sla_clocks_tenant_id'), 'sla_clocks', ['tenant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('vendor_type', sa.String(length=64), nullable=False),
    sa.Column('tax_registration_encrypted', sa.Text(), nullable=True),
    sa.Column('bank_details_encrypted', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'vendor_code', name='uq_vendor_code')
    )
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('vessel_schedules',
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('vessel_id', sa.UUID(), nullable=False),
    sa.Column('voyage_number', sa.Text(), nullable=False),
    sa.Column('port_rotation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cy_cutoff', sa.Date(), nullable=True),
    sa.Column('si_cutoff', sa.Date(), nullable=True),
    sa.Column('vgm_cutoff', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_states',
    sa.Column('state_machine_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_machine_id'], ['state_machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_machine_id', 'code', name='uq_workflow_state_code')
    )
    op.create_table('agents',
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('coverage_country_id', sa.UUID(), nullable=True),
    sa.Column('coverage_city', sa.Text(), nullable=True),
    sa.Column('services_provided', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('settlement_model', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coverage_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_table('branches',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_branch_tenant_code')
    )
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('business_rule_versions',
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rules.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_rule_id', 'version_number', name='uq_rule_version')
    )
    op.create_table('customer_addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=32), nullable=False),
    sa.Column('line1', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_contacts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('email_encrypted', sa.Text(), nullable=True),
    sa.Column('email_lookup_hash', sa.String(length=64), nullable=True),
    sa.Column('phone_encrypted', sa.Text(), nullable=True),
    sa.Column('phone_lookup_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_credit_overrides',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_portal_users',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'user_id', name='uq_customer_portal_user')
    )
    op.create_table('rates',
    sa.Column('rate_number', sa.Text(), nullable=False),
    sa.Column('rate_type', sa.String(length=32), nullable=False),
    sa.Column('rate_category', sa.String(length=32), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('service_name', sa.Text(), nullable=True),
    sa.Column('origin_location_id', sa.UUID(), nullable=True),
    sa.Column('destination_location_id', sa.UUID(), nullable=True),
    sa.Column('via_routing', sa.Text(), nullable=True),
    sa.Column('commodity_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rate_number', name='uq_rate_number')
    )
    op.create_index(op.f('ix_rates_tenant_id'), 'rates', ['tenant_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('rfq_number', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('origin_location_id', sa.UUID(), nullable=True),
    sa.Column('destination_location_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('service_type', sa.String(length=32), nullable=True),
    sa.Column('incoterm_code', sa.Text(), nullable=True),
    sa.Column('movement_type', sa.String(length=32), nullable=True),
    sa.Column('cargo_ready_date', sa.Date(), nullable=True),
    sa.Column('preferred_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('required_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_carrier_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['incoterm_code'], ['incoterms.code'], ),
    sa.ForeignKeyConstraint(['origin_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['preferred_carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rfq_number', name='uq_rfq_number')
    )
    op.create_index(op.f('ix_rfqs_tenant_id'), 'rfqs', ['tenant_id'], unique=False)
    op.create_table('route_legs',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=False),
    sa.Column('to_location_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=True),
    sa.Column('vessel_id', sa.UUID(), nullable=True),
    sa.Column('flight_schedule_id', sa.UUID(), nullable=True),
    sa.Column('etd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transit_time_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_transshipment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['flight_schedule_id'], ['flight_schedules.id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence', name='uq_route_leg_sequence')
    )
    op.create_table('rule_evaluation_logs',
    sa.Column('business_rule_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_rule_id'], ['business_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_evaluation_logs_business_rule_id'), 'rule_evaluation_logs', ['business_rule_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('state_machine_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('current_state_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_state_id'], ['workflow_states.id'], ),
    sa.ForeignKeyConstraint(['state_machine_id'], ['state_machines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_entity_id'), 'workflow_instances', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_tenant_id'), 'workflow_instances', ['tenant_id'], unique=False)
    op.create_table('workflow_transitions',
    sa.Column('state_machine_id', sa.UUID(), nullable=False),
    sa.Column('from_state_id', sa.UUID(), nullable=False),
    sa.Column('to_state_id', sa.UUID(), nullable=False),
    sa.Column('required_permission', sa.String(length=128), nullable=True),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('guard_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_state_id'], ['workflow_states.id'], ),
    sa.ForeignKeyConstraint(['state_machine_id'], ['state_machines.id'], ),
    sa.ForeignKeyConstraint(['to_state_id'], ['workflow_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_rate_agreements',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('rate_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('quotation_number', sa.Text(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('parent_quotation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'quotation_number', name='uq_quotation_number')
    )
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    op.create_table('rate_versions',
    sa.Column('rate_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_id', 'version_number', name='uq_rate_version')
    )
    op.create_table('rfq_cargo_lines',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=True),
    sa.Column('package_type_code', sa.Text(), nullable=True),
    sa.Column('packages', sa.Integer(), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('length_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cargo_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=True),
    sa.Column('is_stackable', sa.Boolean(), nullable=False),
    sa.Column('is_tiltable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['package_type_code'], ['package_types.code'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfq_container_requirements',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('container_type_code', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('weight_per_container_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temperature_unit', sa.String(length=8), nullable=True),
    sa.Column('genset_required', sa.Boolean(), nullable=False),
    sa.Column('soc_coc', sa.String(length=8), nullable=True),
    sa.Column('oog_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['container_type_code'], ['container_types.code'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfq_parties',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('party_role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address_encrypted', sa.Text(), nullable=True),
    sa.Column('contact_encrypted', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfq_special_requirements',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('dgr_flag', sa.Boolean(), nullable=False),
    sa.Column('temperature_controlled', sa.Boolean(), nullable=False),
    sa.Column('temperature_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=False),
    sa.Column('insurance_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fumigation_required', sa.Boolean(), nullable=False),
    sa.Column('inspection_required', sa.Boolean(), nullable=False),
    sa.Column('special_handling_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('customs_docs_required', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('lc_flag', sa.Boolean(), nullable=False),
    sa.Column('lc_number', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id')
    )
    op.create_table('user_branch_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'branch_id', 'role_id', name='uq_user_branch_role')
    )
    op.create_table('workflow_transition_history',
    sa.Column('workflow_instance_id', sa.UUID(), nullable=False),
    sa.Column('from_state_id', sa.UUID(), nullable=False),
    sa.Column('to_state_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_transition_history_workflow_instance_id'), 'workflow_transition_history', ['workflow_instance_id'], unique=False)
    op.create_table('bookings',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id')
    )
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_number', sa.Text(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id'),
    sa.UniqueConstraint('tenant_id', 'job_number', name='uq_job_number')
    )
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('quotation_approvals',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('approval_type', sa.String(length=32), nullable=False),
    sa.Column('approver_role', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_options',
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('primary_rate_version_id', sa.UUID(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_sell', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_margin', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('margin_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('is_below_margin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['primary_rate_version_id'], ['rate_versions.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_lines',
    sa.Column('rate_version_id', sa.UUID(), nullable=False),
    sa.Column('charge_code', sa.Text(), nullable=False),
    sa.Column('rate_basis', sa.String(length=32), nullable=False),
    sa.Column('weight_break_from', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('weight_break_to', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('container_type_code', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charge_code'], ['charge_codes.code'], ),
    sa.ForeignKeyConstraint(['container_type_code'], ['container_types.code'], ),
    sa.ForeignKeyConstraint(['rate_version_id'], ['rate_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_surcharges',
    sa.Column('rate_version_id', sa.UUID(), nullable=False),
    sa.Column('charge_code', sa.Text(), nullable=False),
    sa.Column('basis', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('applicable_from', sa.Date(), nullable=True),
    sa.Column('applicable_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charge_code'], ['charge_codes.code'], ),
    sa.ForeignKeyConstraint(['rate_version_id'], ['rate_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotation_lines',
    sa.Column('quotation_option_id', sa.UUID(), nullable=False),
    sa.Column('charge_code', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('rate_version_id', sa.UUID(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sell_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['charge_code'], ['charge_codes.code'], ),
    sa.ForeignKeyConstraint(['quotation_option_id'], ['quotation_options.id'], ),
    sa.ForeignKeyConstraint(['rate_version_id'], ['rate_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('master_shipment_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['master_shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_shipments_customer_id'), 'shipments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tenant_id'), 'shipments', ['tenant_id'], unique=False)
    op.create_table('cargo',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('volume', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('container_no', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_lines',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_entries',
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reversal_of_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['financial_entries.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_entries_entry_date'), 'financial_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_financial_entries_tenant_id'), 'financial_entries', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('revenue_lines',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('charge_code', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_legs',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('etd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_legs_shipment_id'), 'shipment_legs', ['shipment_id'], unique=False)
    op.create_table('tracking_events',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_events_event_time'), 'tracking_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_type'), 'tracking_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tracking_events_shipment_id'), 'tracking_events', ['shipment_id'], unique=False)
    op.create_table('packages',
    sa.Column('cargo_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dimensions', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    op.drop_index(op.f('ix_tracking_events_shipment_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_event_type'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_event_time'), table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_shipment_legs_shipment_id'), table_name='shipment_legs')
    op.drop_table('shipment_legs')
    op.drop_table('revenue_lines')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_financial_entries_tenant_id'), table_name='financial_entries')
    op.drop_index(op.f('ix_financial_entries_entry_date'), table_name='financial_entries')
    op.drop_table('financial_entries')
    op.drop_table('documents')
    op.drop_table('cost_lines')
    op.drop_table('containers')
    op.drop_table('cargo')
    op.drop_index(op.f('ix_shipments_tenant_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_customer_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('quotation_lines')
    op.drop_table('rate_surcharges')
    op.drop_table('rate_lines')
    op.drop_table('quotation_options')
    op.drop_table('quotation_approvals')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_workflow_transition_history_workflow_instance_id'), table_name='workflow_transition_history')
    op.drop_table('workflow_transition_history')
    op.drop_table('user_branch_roles')
    op.drop_table('rfq_special_requirements')
    op.drop_table('rfq_parties')
    op.drop_table('rfq_container_requirements')
    op.drop_table('rfq_cargo_lines')
    op.drop_table('rate_versions')
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_table('agent_rate_agreements')
    op.drop_table('workflow_transitions')
    op.drop_index(op.f('ix_workflow_instances_tenant_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_rule_evaluation_logs_business_rule_id'), table_name='rule_evaluation_logs')
    op.drop_table('rule_evaluation_logs')
    op.drop_table('route_legs')
    op.drop_index(op.f('ix_rfqs_tenant_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_rates_tenant_id'), table_name='rates')
    op.drop_table('rates')
    op.drop_table('customer_portal_users')
    op.drop_table('customer_credit_overrides')
    op.drop_table('customer_contacts')
    op.drop_table('customer_addresses')
    op.drop_table('business_rule_versions')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('workflow_states')
    op.drop_table('vessel_schedules')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_sla_clocks_tenant_id'), table_name='sla_clocks')
    op.drop_index(op.f('ix_sla_clocks_entity_id'), table_name='sla_clocks')
    op.drop_table('sla_clocks')
    op.drop_index(op.f('ix_routes_tenant_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('flight_schedules')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_business_rules_tenant_id'), table_name='business_rules')
    op.drop_table('business_rules')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('zones')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_state_machines_tenant_id'), table_name='state_machines')
    op.drop_table('state_machines')
    op.drop_index(op.f('ix_sla_definitions_tenant_id'), table_name='sla_definitions')
    op.drop_table('sla_definitions')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reconciliation_variances_tenant_id'), table_name='reconciliation_variances')
    op.drop_table('reconciliation_variances')
    op.drop_table('locations')
    op.drop_table('exchange_rates')
    op.drop_table('uld_types')
    op.drop_table('tenants')
    op.drop_table('processed_events')
    op.drop_table('permissions')
    op.drop_table('package_types')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('incoterms')
    op.drop_table('fact_tracking_events')
    op.drop_table('fact_shipments')
    op.drop_table('fact_financial_entries')
    op.drop_table('document_types')
    op.drop_table('dim_time')
    op.drop_table('dim_routes')
    op.drop_table('dim_customers')
    op.drop_table('dim_carriers')
    op.drop_table('currencies')
    op.drop_table('countries')
    op.drop_table('container_types')
    op.drop_index(op.f('ix_commodities_hs_code'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_table('charge_codes')
    op.drop_table('carriers')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
