"""API v1 endpoint modules."""

from app.api.v1.endpoints import (
    analytics,
    audit,
    auth,
    commercial_calculations,
    commercial_master_data,
    commercial_parties,
    commercial_quotations,
    commercial_rates,
    commercial_rfqs,
    commercial_routes,
    commercial_schedules,
    financial,
    health,
    rules,
    search,
    shipments,
    users,
    workflows,
)

__all__ = [
    "analytics",
    "audit",
    "auth",
    "commercial_calculations",
    "commercial_master_data",
    "commercial_parties",
    "commercial_quotations",
    "commercial_rates",
    "commercial_rfqs",
    "commercial_routes",
    "commercial_schedules",
    "financial",
    "health",
    "rules",
    "search",
    "shipments",
    "users",
    "workflows",
]
